name: GitHub-Profile-3D-Contrib-fixed

on:
  schedule:
    - cron: "0 15,18,21,3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: gumbobrot/github-profile-3d-contrib@0.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Check for changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if ! git diff --cached --quiet; then
            git commit -m "generated"
            git push
          else
            echo "No changes to commit."
          fi
